### ISSUE TITLE
router should be able to use both views links or controller methods

### ISSUE THREAD

**Issue by MohamedAmine-C** [MohamedAmine-C/Uxie#13]

**Comment by CaddyDz** [comment]
Do you mean function closure that is able to return a view or a direct link?

**Comment by MohamedAmine-C** [comment]
i mean something like this : 
`protected $routes = [
        'index'       => 'views/index',                                   // this line will return the index directly
        'error'  => 'ErrorsController@displayError',    // this line will execute a method within a controller
    ];`

**Comment by CaddyDz** [comment]
I see
I think a better approach would be a helper method to retrieve a view directly similar to the one introduced in Laravel 5.5 [here](https://laravel.com/docs/5.5/routing#view-routes)

**Comment by MohamedAmine-C** [comment]
yeah it's already exist  
`public static function getView(string $view, array $data = null)` on router.php line 47
example : 
`return Router::getView('index', ['name' => 'you', 'age' => '99']);`
the problem is in routes used by user how to know if a route is a link to a view or a method in controller ?
there is some solution but i'm not satisfied with them  as they seems some how messy or will cause some bugs on exceptional conditions.

**Comment by CaddyDz** [comment]
It looks pretty good
I'll think of a solution
